language: ruby
bundler_args: --without yard guard benchmarks
script: "bundle exec rake ci"
rvm:
  - 1.9.3
  - 2.0.0
  - rbx-19mode
  - jruby-19mode
  - ruby-head
notifications:
  irc:
    channels:
      - "irc.freenode.org#rom-rb"
    on_success: never
    on_failure: change
  email:
    on_success: never
    on_failure: change
